// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fnpmaffptlkwjioccifp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZucG1hZmZwdGxrd2ppb2NjaWZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA4NTc0MTksImV4cCI6MjA1NjQzMzQxOX0.c6IqlWlVDK0aUsT84b00t1zIj3DKI4i0bMef3NuMnq0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);